apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp
  namespace: efs-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 3Gi      # Only needed per Kubernetes convention, can be anything since the storage will be elastic