apiVersion: apps/v1
kind: Deployment
metadata:
  name: mas-myapp
  namespace: mas-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mas-myapp
  template:
    metadata:
      labels:
        app: mas-myapp
    spec:
      containers:
        - name: mas-myapp
          image: aputra/myapp-195:v2
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 100m