apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
  namespace: myapp2-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
        - name: myapp2
          image: aputra/myapp-195:v2      # Example app
          ports:
            - name: http
              containerPort: 8080
          resources:      # Resource blocks are required for deployments with Horizontal Pod Autoscaler (HPA) on EKS, not limits, to calculate usage in %
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 500m